# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OJPtPGUeI21-kpBl3VJk1VzaUtuQnKF2
"""

import tensorflow as tf
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import layers, models

# Data Preparation
train_datagen = ImageDataGenerator(rescale=1/255.0, validation_split=0.2,
                                   rotation_range=20, zoom_range=0.2,
                                   horizontal_flip=True)

train_gen = train_datagen.flow_from_directory(
    "data/",
    target_size=(128,128),
    batch_size=32,
    subset="training"
)

val_gen = train_datagen.flow_from_directory(
    "data/",
    target_size=(128,128),
    batch_size=32,
    subset="validation"
)

# Model
base = EfficientNetB0(weights="imagenet", include_top=False,
                      input_shape=(128,128,3))
base.trainable = False

model = models.Sequential([
    base,
    layers.GlobalAveragePooling2D(),
    layers.Dense(128, activation="relu"),
    layers.Dropout(0.3),
    layers.Dense(train_gen.num_classes, activation="softmax")
])

model.compile(optimizer=tf.keras.optimizers.Adam(1e-4),
              loss="categorical_crossentropy",
              metrics=["accuracy"])

history = model.fit(train_gen, validation_data=val_gen, epochs=20)

model.save("efficientnet_model.h5")